import { AccountRepository } from "@app/account/repositories/account.repository.js";
import { type IAccountRepository } from "@app/account/contracts/repositories/account.repository.js";
import { HotpService } from "@app/account/services/hotp.service.js";
import { type IHotpService } from "@app/account/contracts/services/hotp.service.js";
import { TotpService } from "@app/account/services/totp.service.js";
import { type ITotpService } from "@app/account/contracts/services/totp.service.js";
import { DeleteAccountUseCase } from "@app/account/useCases/deleteAccount.useCase.js";
import { type IDeleteAccountUseCase } from "@app/account/contracts/useCases/deleteAccount.useCase.js";
import { EditAccountUseCase } from "@app/account/useCases/editAccount.useCase.js";
import { type IEditAccountUseCase } from "@app/account/contracts/useCases/editAccount.useCase.js";
import { FindAccountUseCase } from "@app/account/useCases/findAccount.useCase.js";
import { type IFindAccountUseCase } from "@app/account/contracts/useCases/findAccount.useCase.js";
import { RegisterAccountUseCase } from "@app/account/useCases/registerAccount.useCase.js";
import { type IRegisterAccountUseCase } from "@app/account/contracts/useCases/registerAccount.useCase.js";
import { container } from "tsyringe";

container.register<IAccountRepository>("IAccountRepository", { useClass: AccountRepository });
container.register<IHotpService>("IHotpService", { useClass: HotpService });
container.register<ITotpService>("ITotpService", { useClass: TotpService });
container.register<IDeleteAccountUseCase>("IDeleteAccountUseCase", { useClass: DeleteAccountUseCase });
container.register<IEditAccountUseCase>("IEditAccountUseCase", { useClass: EditAccountUseCase });
container.register<IFindAccountUseCase>("IFindAccountUseCase", { useClass: FindAccountUseCase });
container.register<IRegisterAccountUseCase>("IRegisterAccountUseCase", { useClass: RegisterAccountUseCase });
